name: test workflow
on:
  push:
jobs:
  testjob:
    runs-on: ubuntu-latest
    env:
        NAME: "Shibil"
    steps:
      - name: Print env
        run: echo $NAME
      - name: print name again
        run: echo $NAME
      
